id: A262C155E
base_file: fEDBB.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:03:06.783291
  last_modified_at: 2022-05-31 05:03:06.783317
