id: A262C155E
base_file: f82D4.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:03:06.779293
  last_modified_at: 2022-05-31 05:03:06.779299
