id: A262C155E
base_file: fBFE8.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:03:06.781459
  last_modified_at: 2022-05-31 05:03:06.781464
